export const USER_UPDATE_PENDING = 'USER_UPDATE_PENDING'
export const USER_UPDATE_FULFILLED = 'USER_UPDATE_FULFILLED'
export const USER_UPDATE_REJECTED = 'USER_UPDATE_REJECTED'

export const USER_CREDENTIALS_UPDATE = 'USER_CREDENTIALS_UPDATE'

export const USER_INIT = 'USER_INIT'
