language: node_js
node_js:
- stable
script:
- yarn lint
- yarn stylint
- yarn test:coverage
- yarn build
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
env:
  matrix:
  - secure: GhV8vaT7ITa3Yd38ez/etrauTtCeSTfX6A03JyoN/G1kGu97/lAAjkEtDSxJCbhv7ngJVXAJTtVeKUCOL/8eVqdcloEdlIhg1IlGHYkM5orZabAvlKTvMPfvQime7evIQ8X6bJqMfr6qZq4PX6FTzLOQoWxBRp7uJtT+rNu5axh0vISMrcY1T820yZD6Fs+qTKddKomKTybd4YKgauJy1wfE8kxsIaZyih/aqoJrRga8R7YFVhcvZlRVtd6uKJ3k8ZvBYYXcr7XDxHNOb9yKzrYQ5S08ZNyroUXNjnL3NNKTUoAlFdeGKktd0Hr7bgnHCh0zwSlA30194M9iplwAGDMkYVy9oX6UhBvZgZ3zJQ0lo/yQOfwFxE2MZL1gNOScoLrOFkYcKu68PG6EPDT/v3eXSLafp50mPI/gPBlE/uCKiH6aEN1aiUPTimkIkyZPf6r7ySYtdNhUUDX9XVbaRoVivUY+RyY+V840l1L695/xIjKxngSk3jJ9KOkkxfftvlxHGWfsSM3Kz9HRZ9YJiEAxfbInXD6suNeU4iBbx1RO/FK2kNdhOSXPxRAsM5C6/OD5Lxb6baKkXg9iWFgN9psGBFSMNVrylcQQq+WRAQNDQ3uw2sxogn1fKRSQ4JMk4r3hP/CxRQiSbdHXYxM3FUNa/V4sVmV4PHdcfi3IipE=
  - secure: Knqi8VaHtLx1bOgKg39P9z/AcHnh+MUqJE2ebgD2ENNXYPCNUo5k9Ce8Tlohm1CcCl5zn43UB1jf0FsuDAm9z7RqN8U7hXGJwsVN0MzdFPEPe2hELXLgFtDtztmyci4FmKzWGqvBSJ68lNhmJGSCLrXQKXBlXgo0CyHJ5FaNa+4zjg/MoV6T5FMVQGfnJA2EY+RrVBX3PGJ4839t/jrJ2xIBwBsOJEb8k81s0Ls5emBDH4APqrMwLjzLtjtYun5zqlPAWxyPb3lYp5qRn4TZx0c1maBroUzFjTjBkcUtvv1VozShn9a27gDiU7n49VvKVl3rwUXpC1c717LSN7EhciX5hdGRX7InR+QXeVFu5/z5VkSJlCnfthGOKG2d4m6Ta5c4aoz63ZjhF0xN5njs8Q7mifsUB4uTi5e/A+S1FvXBLKdmO+rpbl7C8w+2Yz/T0C1nvlCMDVXdONTNHGPvJiSWefof2fpIQYY5P36CXQIZmaBrL5hPIaJetGiNCi8WRhRNMaRcUNPbZ56YBCZTMcJbs4g3u3Aw0aMWarXBqxppabLOWb6Da/FHZdxUKNWwPJtnflWczHAl32I0wYTwCkYd48wcjoOIT/LS8wuqvwfbxKtHqQ14PzalVNokK8ikJy/lmJEqIzzvyYalNccL/9Nf17Yax25/wmQwvrtND5U=
