language: node_js
node_js:
- stable
script:
- yarn lint
- yarn stylint
- yarn test:coverage
- yarn build
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
env:
  matrix:
    secure: MWWq0wK6eaCPpznIlQiFVThitN9uUFQSLwMi9SdHOKOBssuNNNbT1WCjzZ3rJSNMQNccMFskaXvNopc9ZYeuSAfl9tX8/fbLECW2Q+b8qJ3FnbLDgdj/ou4GmetqOS9bHIpthmB8zEbjZtRAMWgbOU2UMfHkX3psgwxRRigDrSCKVvAmp6gaLN9nhSNb27BglkH4qDaTAypSicq9s6zzUg5S23/Hk/KfS9u8JGaamOjB5l/Y756SUCr+eB90S5jUDdm3Qx8Io8bpDjnpFIZWT9Nd5aIhPbf0mz0S8k2i6JqV4ynb+ETXQNd7VvqLk0hO4zwheYSaevhu3zSAdNVbYyGzyvG+jCAqY+fqqMLL3THtupUIav7LOgEVK1sWy1oiKE78EP3K7o6uA3/u9eCWeGOebnDHUp1ZkrasNyJgNwT1Yh4hCG8/jzp2UgMcomW5VvVNg0L1LkJubRwS+rpUzGTvvARq1+hP+6WFmpdTHY1E59Ev4755caXVZnO1o+qG69wIfP+dD8W8+uaSHal6Uy4NL8zCHmwZUUE6WoVXybC4jjpxNhwagpBs5+ffQPFV7mOwvwOohR1FkE71hp1v80ncdrWAS2bQBorcfwPi84K2T0j348hO1Xio9bChjrem/p8T8I1noRopPzJJ+P43SIA6odnGYgHKvKcsHd4Xnk0=
