language: node_js
node_js:
  - "stable"
script:
  - "yarn lint"
  - "yarn stylint"
  - "yarn build"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
