export const AUTH_LOGIN_PENDING = "AUTH_LOGIN_PENDING";
export const AUTH_LOGIN_FULFILLED = "AUTH_LOGIN_FULFILLED";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const USER_INIT = "USER_INIT";

export const USER_CREDENTIALS_UPDATE = "USER_CREDENTIALS_UPDATE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
