export const RESETTING_PASSWORD_PENDING = "RESETTING_PASSWORD_PENDING";
export const RESETTING_PASSWORD_FULFILLED = "RESETTING_PASSWORD_FULFILLED";
export const RESETTING_PASSWORD_REJECTED = "RESETTING_PASSWORD_REJECTED";

export const RESETTING_PASSWORD_SEND_EMAIL_PENDING =
    "RESETTING_PASSWORD_SEND_EMAIL_PENDING";
export const RESETTING_PASSWORD_SEND_EMAIL_FULFILLED =
    "RESETTING_PASSWORD_SEND_EMAIL_FULFILLED";
export const RESETTING_PASSWORD_SEND_EMAIL_REJECTED =
    "RESETTING_PASSWORD_SEND_EMAIL_REJECTED";

export const CHANGE_PASSWORD_PENDING = "CHANGE_PASSWORD_PENDING";
export const CHANGE_PASSWORD_FULFILLED = "CHANGE_PASSWORD_FULFILLED";
export const CHANGE_PASSWORD_REJECTED = "CHANGE_PASSWORD_REJECTED";
